export const MERGEABLE_MARKER = '^lm'

export const MERGE_HAD_NO_DIFFERENCES_ERROR = 'MERGE_HAD_NO_DIFFERENCES_ERROR'
export const WRONG_TYPE_GIVEN_EXPECTED_OBJECT = 'WRONG_TYPE_GIVEN_EXPECTED_OBJECT'
